version: "3.9"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf 
      - /data/apps/ecommerce-project/redis:/var/lib/redis

  mongo:
    image: "mongo:bionic"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ecommerce-app
      - MONGO_INITDB_ROOT_USERNAME=ecommerce
      - MONGO_INITDB_ROOT_PASSWORD=chungnt-ngoclt
    volumes:
      - /data/apps/ecommerce-project/mongodb:/data/db

  neo4j:
    image: "neo4j:4.2"
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_AUTH=neo4j/chungnt-ngoclt
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import
      - ./neo4j/conf:/conf
      - /data/apps/ecommerce-project/neo4j:/var/lib/neo4j/data

  mysql:
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=ecommerce
      - MYSQL_PASSWORD=chungnt-ngoclt
      # Password for root access
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /data/apps/ecommerce-project/mysql:/var/lib/mysql
