package com.ecommerce.crawler.model;

import com.ecommerce.model.data.mysql.Product;
import com.ecommerce.util.JacksonHelper;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.IOException;
import java.util.List;

/**
 *
 * @author ngoclt2
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class TikiProduct extends BaseModel {

    private long id;
    private String name;
    private String brandName;
    private String shortDescription;
    private long price;
    private String thumbUrl;
    private double ratingAverage;
    private int reviewCount;

    public TikiProduct() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @JsonProperty("brand_name")
    public String getBrandName() {
        return brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    @JsonProperty("short_description")
    public String getShortDescription() {
        return shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    public long getPrice() {
        return price;
    }

    public void setPrice(long price) {
        this.price = price;
    }

    @JsonProperty("thumbnail_url")
    public String getThumbUrl() {
        return thumbUrl;
    }

    public void setThumbUrl(String thumbUrl) {
        this.thumbUrl = thumbUrl;
    }

    @JsonProperty("rating_average")
    public double getRatingAverage() {
        return ratingAverage;
    }

    public void setRatingAverage(double ratingAverage) {
        this.ratingAverage = ratingAverage;
    }

    @JsonProperty("review_count")
    public int getReviewCount() {
        return reviewCount;
    }

    public void setReviewCount(int reviewCount) {
        this.reviewCount = reviewCount;
    }

    public static Product toProductEntity(TikiProduct tikiProduct) {
        Product product = new Product();
        product.setId(tikiProduct.getId());
        product.setName(tikiProduct.getName());
        product.setCategory(0);
        product.setBrandName(tikiProduct.getBrandName());
        product.setShortDescription(tikiProduct.getShortDescription());
        product.setPrice(tikiProduct.getPrice());
        product.setThumbUrl(tikiProduct.getThumbUrl());
        product.setRemainQuantity(1000);
        product.setRatingAvg(tikiProduct.getRatingAverage());
        return product;
    }

    public static void main(String[] args) throws IOException {
        String test = "[\n"
            + "    {\n"
            + "      \"id\": 73795621,\n"
            + "      \"sku\": \"4288839952148\",\n"
            + "      \"name\": \"Apple Macbook Air 2020 M1 - 13 Inchs (Apple M1/ 8GB/ 256GB) - Hàng Chính Hãng-\",\n"
            + "      \"url_key\": \"apple-macbook-air-2020-m1-13-inchs-apple-m1-8gb-256gb-hang-chinh-hang-p73795621\",\n"
            + "      \"url_path\": \"apple-macbook-air-2020-m1-13-inchs-apple-m1-8gb-256gb-hang-chinh-hang-p73795621.html?src=ss-organic\",\n"
            + "      \"type\": \"configurable\",\n"
            + "      \"brand_name\": \"Apple\",\n"
            + "      \"short_description\": \"Hiệu năng mạnh mẽ\\nMacBook Air mới sử dụng chip M1 có CPU 8 lõi, được chia thành 4 lõi hiệu suất cao (High Performance) và 4 lõi hiệu quả (High Efficiency) cùng với Neural Engine 16 lõi.\\n\\n\\nNó cũng bao...\",\n"
            + "      \"price\": 24865000,\n"
            + "      \"list_price\": 29990000,\n"
            + "      \"badges\": [\n"
            + "        {\n"
            + "          \"price\": 4144167,\n"
            + "          \"month\": \"6\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"text\": \"Trả góp 0%\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"badges_new\": [\n"
            + "        {\n"
            + "          \"placement\": \"benefits\",\n"
            + "          \"type\": \"benefits_badge\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/ba/4e/6e/26e9f2487e9f49b7dcf4043960e687dd.png\",\n"
            + "          \"icon_width\": 18,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"Trả góp\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"discount\": 5125000,\n"
            + "      \"discount_rate\": 17,\n"
            + "      \"rating_average\": 0,\n"
            + "      \"review_count\": 0,\n"
            + "      \"order_count\": 0,\n"
            + "      \"favourite_count\": 0,\n"
            + "      \"thumbnail_url\": \"https://salt.tikicdn.com/cache/280x280/ts/product/92/98/f9/32568923c4c42a13346ca55c8bd473fb.jpg\",\n"
            + "      \"thumbnail_width\": 280,\n"
            + "      \"thumbnail_height\": 280,\n"
            + "      \"has_ebook\": false,\n"
            + "      \"inventory_status\": \"available\",\n"
            + "      \"is_visible\": true,\n"
            + "      \"productset_id\": 2493,\n"
            + "      \"is_flower\": false,\n"
            + "      \"is_gift_card\": false,\n"
            + "      \"inventory\": {\n"
            + "        \"fulfillment_type\": \"dropship\"\n"
            + "      },\n"
            + "      \"url_attendant_input_form\": \"\",\n"
            + "      \"option_color\": [\n"
            + "        {\n"
            + "          \"spid\": 76756095,\n"
            + "          \"display_name\": \"Gold\",\n"
            + "          \"is_default\": 1,\n"
            + "          \"price\": 24865000,\n"
            + "          \"list_price\": 29990000,\n"
            + "          \"thumbnail\": \"https://salt.tikicdn.com/cache/200x200/ts/product/92/98/f9/32568923c4c42a13346ca55c8bd473fb.jpg\",\n"
            + "          \"small_thumbnail\": \"https://salt.tikicdn.com/cache/64x64/ts/product/92/98/f9/32568923c4c42a13346ca55c8bd473fb.jpg\",\n"
            + "          \"url_path\": \"apple-macbook-air-2020-m1-13-inchs-apple-m1-8gb-256gb-hang-chinh-hang-p73795621.html?spid=76756095&src=ss-organic\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"spid\": 76756096,\n"
            + "          \"display_name\": \"Silver\",\n"
            + "          \"is_default\": 0,\n"
            + "          \"price\": 25990000,\n"
            + "          \"list_price\": 29990000,\n"
            + "          \"thumbnail\": \"https://salt.tikicdn.com/cache/200x200/ts/product/1d/44/49/7f6ffac91324c3af1577b3d49ac14843.jpg\",\n"
            + "          \"small_thumbnail\": \"https://salt.tikicdn.com/cache/64x64/ts/product/1d/44/49/7f6ffac91324c3af1577b3d49ac14843.jpg\",\n"
            + "          \"url_path\": \"apple-macbook-air-2020-m1-13-inchs-apple-m1-8gb-256gb-hang-chinh-hang-p73795621.html?spid=76756096&src=ss-organic\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"spid\": 94298787,\n"
            + "          \"display_name\": \"Grey\",\n"
            + "          \"is_default\": 0,\n"
            + "          \"price\": 25990000,\n"
            + "          \"list_price\": 29990000,\n"
            + "          \"thumbnail\": \"https://salt.tikicdn.com/cache/200x200/ts/product/ad/46/16/e453b63d9655155be9ee2dc9baab0fb9.jpg\",\n"
            + "          \"small_thumbnail\": \"https://salt.tikicdn.com/cache/64x64/ts/product/ad/46/16/e453b63d9655155be9ee2dc9baab0fb9.jpg\",\n"
            + "          \"url_path\": \"apple-macbook-air-2020-m1-13-inchs-apple-m1-8gb-256gb-hang-chinh-hang-p73795621.html?spid=94298787&src=ss-organic\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"stock_item\": {\n"
            + "        \"qty\": 8,\n"
            + "        \"min_sale_qty\": 1,\n"
            + "        \"max_sale_qty\": 5,\n"
            + "        \"preorder_date\": false\n"
            + "      },\n"
            + "      \"salable_type\": \"\",\n"
            + "      \"seller_product_id\": 76756095,\n"
            + "      \"installment_info\": {\n"
            + "        \"price\": 4144167,\n"
            + "        \"month\": \"6\",\n"
            + "        \"redirect_url\": \"https://tiki.vn/installment?masterId=73795621&spid=76756095\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": 73795655,\n"
            + "      \"sku\": \"5048489092616\",\n"
            + "      \"name\": \"Apple Macbook Pro 2020 M1 - 13 Inchs (Apple M1/ 8GB/ 256GB) - Hàng Chính Hãng\",\n"
            + "      \"url_key\": \"apple-macbook-pro-2020-m1-13-inchs-apple-m1-8gb-256gb-hang-chinh-hang-p73795655\",\n"
            + "      \"url_path\": \"apple-macbook-pro-2020-m1-13-inchs-apple-m1-8gb-256gb-hang-chinh-hang-p73795655.html?src=ss-organic\",\n"
            + "      \"type\": \"configurable\",\n"
            + "      \"brand_name\": \"Apple\",\n"
            + "      \"short_description\": \"Thiết kế trau chuốt từng đường nét, trải nghiệm hình ảnh sắc nét với màn hình Retina\\nVẫn kế thừa thiết kế từ người tiềm nhiệm trước đó của mình, Macbook Pro 2020 M1 vẫn sở hữu thiết kế nhôm nguyên...\",\n"
            + "      \"price\": 30899000,\n"
            + "      \"list_price\": 34990000,\n"
            + "      \"badges\": [\n"
            + "        {\n"
            + "          \"option\": \"2h\",\n"
            + "          \"code\": \"fast_delivery\",\n"
            + "          \"text\": \"Giao nhanh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"code\": \"tikinow\",\n"
            + "          \"text\": \"tikinow\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"code\": \"leadtime\",\n"
            + "          \"text\": \"GIAO NGAY 2H - 3H\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"price\": 5149833,\n"
            + "          \"month\": \"6\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"text\": \"Trả góp 0%\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"badges_new\": [\n"
            + "        {\n"
            + "          \"placement\": \"service\",\n"
            + "          \"type\": \"service_badge\",\n"
            + "          \"code\": \"tikinow\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/9f/32/dd/8a8d39d4453399569dfb3e80fe01de75.png\",\n"
            + "          \"icon_width\": 56,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"GIAO NGAY 2H - 3H\",\n"
            + "          \"text_color\": \"#009900\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"placement\": \"benefits\",\n"
            + "          \"type\": \"benefits_badge\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/ba/4e/6e/26e9f2487e9f49b7dcf4043960e687dd.png\",\n"
            + "          \"icon_width\": 18,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"Trả góp\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"discount\": 4091000,\n"
            + "      \"discount_rate\": 12,\n"
            + "      \"rating_average\": 4.8,\n"
            + "      \"review_count\": 148,\n"
            + "      \"order_count\": 0,\n"
            + "      \"favourite_count\": 0,\n"
            + "      \"thumbnail_url\": \"https://salt.tikicdn.com/cache/280x280/ts/product/90/c1/c8/5dd3cb13601f8a2d1ede1c6af5a18862.jpg\",\n"
            + "      \"thumbnail_width\": 280,\n"
            + "      \"thumbnail_height\": 280,\n"
            + "      \"has_ebook\": false,\n"
            + "      \"inventory_status\": \"available\",\n"
            + "      \"is_visible\": true,\n"
            + "      \"productset_id\": 2493,\n"
            + "      \"is_flower\": false,\n"
            + "      \"is_gift_card\": false,\n"
            + "      \"inventory\": {\n"
            + "        \"fulfillment_type\": \"tiki_delivery\"\n"
            + "      },\n"
            + "      \"url_attendant_input_form\": \"\",\n"
            + "      \"stock_item\": {\n"
            + "        \"qty\": 20,\n"
            + "        \"min_sale_qty\": 1,\n"
            + "        \"max_sale_qty\": 5,\n"
            + "        \"preorder_date\": false\n"
            + "      },\n"
            + "      \"salable_type\": \"\",\n"
            + "      \"seller_product_id\": 73795659,\n"
            + "      \"installment_info\": {\n"
            + "        \"price\": 5149833,\n"
            + "        \"month\": \"6\",\n"
            + "        \"redirect_url\": \"https://tiki.vn/installment?masterId=73795655&spid=73795659\"\n"
            + "      },\n"
            + "      \"bundle_deal\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": 77694498,\n"
            + "      \"sku\": \"8457519972256\",\n"
            + "      \"name\": \"Laptop Asus Vivobook X515MA-BR112T (N4020/ 4G/ 256GB SSD/ 15.6 HD/ Win10) - Hàng Chính Hãng\",\n"
            + "      \"url_key\": \"laptop-asus-vivobook-x515ma-br112t-n4020-4g-256gb-ssd-15-6-hd-win10-hang-chinh-hang-p77694498\",\n"
            + "      \"url_path\": \"laptop-asus-vivobook-x515ma-br112t-n4020-4g-256gb-ssd-15-6-hd-win10-hang-chinh-hang-p77694498.html?src=ss-organic\",\n"
            + "      \"type\": \"simple\",\n"
            + "      \"brand_name\": \"Asus\",\n"
            + "      \"short_description\": \"Thiết kế mỏng nhẹ\\nLaptop Asus Vivobook X515MA-BR112T là chiếc laptop hướng đến mọi người như các bạn học sinh, sinh viên và dân văn phòng, với hiệu năng xử lý ổn định và thiết kế đẹp mắt sẵn sáng đáp...\",\n"
            + "      \"price\": 6859000,\n"
            + "      \"list_price\": 7049000,\n"
            + "      \"badges\": [\n"
            + "        {\n"
            + "          \"price\": 1143167,\n"
            + "          \"month\": \"6\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"text\": \"Trả góp 0%\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"badges_new\": [\n"
            + "        {\n"
            + "          \"placement\": \"under_price\",\n"
            + "          \"type\": \"under_price_icon\",\n"
            + "          \"code\": \"is_best_price_guaranteed\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/51/ac/cc/528e80fe3f464f910174e2fdf8887b6f.png\",\n"
            + "          \"icon_width\": 124,\n"
            + "          \"icon_height\": 18,\n"
            + "          \"text\": \"\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"placement\": \"benefits\",\n"
            + "          \"type\": \"benefits_badge\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/ba/4e/6e/26e9f2487e9f49b7dcf4043960e687dd.png\",\n"
            + "          \"icon_width\": 18,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"Trả góp\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"discount\": 190000,\n"
            + "      \"discount_rate\": 3,\n"
            + "      \"rating_average\": 4.7,\n"
            + "      \"review_count\": 13,\n"
            + "      \"order_count\": 0,\n"
            + "      \"favourite_count\": 0,\n"
            + "      \"thumbnail_url\": \"https://salt.tikicdn.com/cache/280x280/ts/product/07/e0/0e/74c646f278ba70fc6c28b8781e30abc3.jpg\",\n"
            + "      \"thumbnail_width\": 280,\n"
            + "      \"thumbnail_height\": 280,\n"
            + "      \"has_ebook\": false,\n"
            + "      \"inventory_status\": \"available\",\n"
            + "      \"is_visible\": true,\n"
            + "      \"productset_id\": 2635,\n"
            + "      \"is_flower\": false,\n"
            + "      \"is_gift_card\": false,\n"
            + "      \"inventory\": {\n"
            + "        \"fulfillment_type\": \"tiki_delivery\"\n"
            + "      },\n"
            + "      \"url_attendant_input_form\": \"\",\n"
            + "      \"stock_item\": {\n"
            + "        \"qty\": 4,\n"
            + "        \"min_sale_qty\": 1,\n"
            + "        \"max_sale_qty\": 1,\n"
            + "        \"preorder_date\": false\n"
            + "      },\n"
            + "      \"salable_type\": \"\",\n"
            + "      \"seller_product_id\": 77694499,\n"
            + "      \"installment_info\": {\n"
            + "        \"price\": 1143167,\n"
            + "        \"month\": \"6\",\n"
            + "        \"redirect_url\": \"https://tiki.vn/installment?masterId=77694498&spid=77694499\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": 58388702,\n"
            + "      \"sku\": \"1018692973686\",\n"
            + "      \"name\": \"Laptop HP 15s-fq1107TU 193Q3PA (Core i3-1005G1/ 4GB DDR4 2666MHz/ 256GB SSD M.2 NVMe/ 15.6 SVA/ Win10) - Hàng Chính Hãng\",\n"
            + "      \"url_key\": \"laptop-hp-15s-fq1107tu-193q3pa-core-i3-1005g1-4gb-ddr4-2666mhz-256gb-ssd-m-2-nvme-15-6-sva-win10-hang-chinh-hang-p58388702\",\n"
            + "      \"url_path\": \"laptop-hp-15s-fq1107tu-193q3pa-core-i3-1005g1-4gb-ddr4-2666mhz-256gb-ssd-m-2-nvme-15-6-sva-win10-hang-chinh-hang-p58388702.html?src=ss-organic\",\n"
            + "      \"type\": \"simple\",\n"
            + "      \"brand_name\": \"HP\",\n"
            + "      \"short_description\": \"Thiết kế sang trọng\\nLaptop HP 15s-fq1107TU được thiết kế với kiểu dáng đẹp mắt, với tông màu bạc sang trọng, các góc cạnh của máy được bo tròn để dễ dàng cho vào balo.\\nBộ vi xử lý mượt mà\\nLaptop HP...\",\n"
            + "      \"price\": 10049000,\n"
            + "      \"list_price\": 10990000,\n"
            + "      \"badges\": [\n"
            + "        {\n"
            + "          \"price\": 1674833,\n"
            + "          \"month\": \"6\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"text\": \"Trả góp 0%\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"badges_new\": [\n"
            + "        {\n"
            + "          \"placement\": \"under_price\",\n"
            + "          \"type\": \"under_price_icon\",\n"
            + "          \"code\": \"is_best_price_guaranteed\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/51/ac/cc/528e80fe3f464f910174e2fdf8887b6f.png\",\n"
            + "          \"icon_width\": 124,\n"
            + "          \"icon_height\": 18,\n"
            + "          \"text\": \"\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"placement\": \"benefits\",\n"
            + "          \"type\": \"benefits_badge\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/ba/4e/6e/26e9f2487e9f49b7dcf4043960e687dd.png\",\n"
            + "          \"icon_width\": 18,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"Trả góp\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"discount\": 941000,\n"
            + "      \"discount_rate\": 9,\n"
            + "      \"rating_average\": 5,\n"
            + "      \"review_count\": 25,\n"
            + "      \"order_count\": 0,\n"
            + "      \"favourite_count\": 0,\n"
            + "      \"thumbnail_url\": \"https://salt.tikicdn.com/cache/280x280/ts/product/ef/18/b8/de3e6dd258a9b8e31c48fb5c3552e210.jpg\",\n"
            + "      \"thumbnail_width\": 280,\n"
            + "      \"thumbnail_height\": 280,\n"
            + "      \"has_ebook\": false,\n"
            + "      \"inventory_status\": \"available\",\n"
            + "      \"is_visible\": true,\n"
            + "      \"productset_id\": 2635,\n"
            + "      \"is_flower\": false,\n"
            + "      \"is_gift_card\": false,\n"
            + "      \"inventory\": {\n"
            + "        \"fulfillment_type\": \"tiki_delivery\"\n"
            + "      },\n"
            + "      \"url_attendant_input_form\": \"\",\n"
            + "      \"stock_item\": {\n"
            + "        \"qty\": 9,\n"
            + "        \"min_sale_qty\": 1,\n"
            + "        \"max_sale_qty\": 1,\n"
            + "        \"preorder_date\": false\n"
            + "      },\n"
            + "      \"salable_type\": \"\",\n"
            + "      \"seller_product_id\": 58388703,\n"
            + "      \"installment_info\": {\n"
            + "        \"price\": 1674833,\n"
            + "        \"month\": \"6\",\n"
            + "        \"redirect_url\": \"https://tiki.vn/installment?masterId=58388702&spid=58388703\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": 55244349,\n"
            + "      \"sku\": \"4991840295953\",\n"
            + "      \"name\": \"Apple Macbook Pro 2020 - 13 Inchs (i5-8th/ 8GB/ 256GB) - Hàng Nhập Khẩu Chính Hãng\",\n"
            + "      \"url_key\": \"apple-macbook-pro-2020-13-inchs-i5-8th-8gb-256gb-hang-nhap-khau-chinh-hang-p55244349\",\n"
            + "      \"url_path\": \"apple-macbook-pro-2020-13-inchs-i5-8th-8gb-256gb-hang-nhap-khau-chinh-hang-p55244349.html?src=ss-organic\",\n"
            + "      \"type\": \"configurable\",\n"
            + "      \"brand_name\": \"Apple\",\n"
            + "      \"short_description\": \"Sự kết hợp giữa công nghệ và thời trang\\nMột chiếc laptop tuyệt đẹp, nhỏ gọn, cao cấp, chắc chắn và tinh xảo đến từng đường nét. Đó là những gì mà chúng ta có thể mô tả về thiết kế của Apple Macbook...\",\n"
            + "      \"price\": 28099000,\n"
            + "      \"list_price\": 36990000,\n"
            + "      \"badges\": [\n"
            + "        {\n"
            + "          \"price\": 4683167,\n"
            + "          \"month\": \"6\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"text\": \"Trả góp 0%\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"badges_new\": [\n"
            + "        {\n"
            + "          \"placement\": \"under_price\",\n"
            + "          \"type\": \"under_price_icon\",\n"
            + "          \"code\": \"is_best_price_guaranteed\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/51/ac/cc/528e80fe3f464f910174e2fdf8887b6f.png\",\n"
            + "          \"icon_width\": 124,\n"
            + "          \"icon_height\": 18,\n"
            + "          \"text\": \"\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"placement\": \"benefits\",\n"
            + "          \"type\": \"benefits_badge\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/ba/4e/6e/26e9f2487e9f49b7dcf4043960e687dd.png\",\n"
            + "          \"icon_width\": 18,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"Trả góp\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"discount\": 8891000,\n"
            + "      \"discount_rate\": 24,\n"
            + "      \"rating_average\": 4.5,\n"
            + "      \"review_count\": 44,\n"
            + "      \"order_count\": 0,\n"
            + "      \"favourite_count\": 0,\n"
            + "      \"thumbnail_url\": \"https://salt.tikicdn.com/cache/280x280/ts/product/e1/68/65/7d2e94f82822f1801f627f52bb640fa4.jpg\",\n"
            + "      \"thumbnail_width\": 280,\n"
            + "      \"thumbnail_height\": 280,\n"
            + "      \"has_ebook\": false,\n"
            + "      \"inventory_status\": \"available\",\n"
            + "      \"is_visible\": true,\n"
            + "      \"productset_id\": 2493,\n"
            + "      \"is_flower\": false,\n"
            + "      \"is_gift_card\": false,\n"
            + "      \"inventory\": {\n"
            + "        \"fulfillment_type\": \"tiki_delivery\"\n"
            + "      },\n"
            + "      \"url_attendant_input_form\": \"\",\n"
            + "      \"stock_item\": {\n"
            + "        \"qty\": 10,\n"
            + "        \"min_sale_qty\": 1,\n"
            + "        \"max_sale_qty\": 1,\n"
            + "        \"preorder_date\": false\n"
            + "      },\n"
            + "      \"salable_type\": \"\",\n"
            + "      \"seller_product_id\": 55244351,\n"
            + "      \"installment_info\": {\n"
            + "        \"price\": 4683167,\n"
            + "        \"month\": \"6\",\n"
            + "        \"redirect_url\": \"https://tiki.vn/installment?masterId=55244349&spid=55244351\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": 72040315,\n"
            + "      \"sku\": \"1764656931789\",\n"
            + "      \"name\": \"Laptop Asus ZenBook UX425EA-BM069T (Core i5-1135G7/ 8GB LPDDR4X 3200MHz (Onboard)/ 512GB SSD M.2 PCIE G3X2/ 14 FHD IPS/ Win10) - Hàng Chính Hãng\",\n"
            + "      \"url_key\": \"laptop-asus-zenbook-ux425ea-bm069t-core-i5-1135g7-8gb-lpddr4x-3200mhz-onboard-512gb-ssd-m-2-pcie-g3x2-14-fhd-ips-win10-hang-chinh-hang-p72040315\",\n"
            + "      \"url_path\": \"laptop-asus-zenbook-ux425ea-bm069t-core-i5-1135g7-8gb-lpddr4x-3200mhz-onboard-512gb-ssd-m-2-pcie-g3x2-14-fhd-ips-win10-hang-chinh-hang-p72040315.html?src=ss-organic\",\n"
            + "      \"type\": \"simple\",\n"
            + "      \"brand_name\": \"Asus\",\n"
            + "      \"short_description\": \"Gọn nhẹ và di chuyển dễ dàng\\nLaptop Asus ZenBook UX425EA-BM069T có thiết kế hoàn toàn bằng kim loại, siêu nhẹ, mỏng và gọn gang. Điều này khiến nó trở thành người bạn đồng hành lý tưởng trong những...\",\n"
            + "      \"price\": 21329000,\n"
            + "      \"list_price\": 22990000,\n"
            + "      \"badges\": [\n"
            + "        {\n"
            + "          \"price\": 3554833,\n"
            + "          \"month\": \"6\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"text\": \"Trả góp 0%\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"badges_new\": [\n"
            + "        {\n"
            + "          \"placement\": \"benefits\",\n"
            + "          \"type\": \"benefits_badge\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/ba/4e/6e/26e9f2487e9f49b7dcf4043960e687dd.png\",\n"
            + "          \"icon_width\": 18,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"Trả góp\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"discount\": 1661000,\n"
            + "      \"discount_rate\": 7,\n"
            + "      \"rating_average\": 4.7,\n"
            + "      \"review_count\": 19,\n"
            + "      \"order_count\": 0,\n"
            + "      \"favourite_count\": 0,\n"
            + "      \"thumbnail_url\": \"https://salt.tikicdn.com/cache/280x280/ts/product/53/cb/0a/126ddb57b0ca3a0d803c0c7a30c311ad.jpg\",\n"
            + "      \"thumbnail_width\": 280,\n"
            + "      \"thumbnail_height\": 280,\n"
            + "      \"has_ebook\": false,\n"
            + "      \"inventory_status\": \"available\",\n"
            + "      \"is_visible\": true,\n"
            + "      \"productset_id\": 2635,\n"
            + "      \"is_flower\": false,\n"
            + "      \"is_gift_card\": false,\n"
            + "      \"inventory\": {\n"
            + "        \"fulfillment_type\": \"tiki_delivery\"\n"
            + "      },\n"
            + "      \"url_attendant_input_form\": \"\",\n"
            + "      \"stock_item\": {\n"
            + "        \"qty\": 9,\n"
            + "        \"min_sale_qty\": 1,\n"
            + "        \"max_sale_qty\": 1,\n"
            + "        \"preorder_date\": false\n"
            + "      },\n"
            + "      \"salable_type\": \"\",\n"
            + "      \"seller_product_id\": 72040316,\n"
            + "      \"installment_info\": {\n"
            + "        \"price\": 3554833,\n"
            + "        \"month\": \"6\",\n"
            + "        \"redirect_url\": \"https://tiki.vn/installment?masterId=72040315&spid=72040316\"\n"
            + "      },\n"
            + "      \"bundle_deal\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": 73795660,\n"
            + "      \"sku\": \"1336358797965\",\n"
            + "      \"name\": \"Apple Macbook Pro 2020 M1 - 13 Inchs (Apple M1/ 8GB/ 512GB) - Hàng Chính Hãng\",\n"
            + "      \"url_key\": \"apple-macbook-pro-2020-m1-13-inchs-apple-m1-8gb-512gb-hang-chinh-hang-p73795660\",\n"
            + "      \"url_path\": \"apple-macbook-pro-2020-m1-13-inchs-apple-m1-8gb-512gb-hang-chinh-hang-p73795660.html?src=ss-organic\",\n"
            + "      \"type\": \"configurable\",\n"
            + "      \"brand_name\": \"Apple\",\n"
            + "      \"short_description\": \"Thiết kế trau chuốt từng đường nét, trải nghiệm hình ảnh sắc nét với màn hình Retina\\nVẫn kế thừa thiết kế từ người tiềm nhiệm trước đó của mình, Macbook Pro 2020 M1 vẫn sở hữu thiết kế nhôm nguyên...\",\n"
            + "      \"price\": 35999000,\n"
            + "      \"list_price\": 39990000,\n"
            + "      \"badges\": [\n"
            + "        {\n"
            + "          \"option\": \"2h\",\n"
            + "          \"code\": \"fast_delivery\",\n"
            + "          \"text\": \"Giao nhanh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"code\": \"tikinow\",\n"
            + "          \"text\": \"tikinow\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"code\": \"leadtime\",\n"
            + "          \"text\": \"GIAO NGAY 2H - 3H\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"price\": 5999833,\n"
            + "          \"month\": \"6\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"text\": \"Trả góp 0%\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"badges_new\": [\n"
            + "        {\n"
            + "          \"placement\": \"service\",\n"
            + "          \"type\": \"service_badge\",\n"
            + "          \"code\": \"tikinow\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/9f/32/dd/8a8d39d4453399569dfb3e80fe01de75.png\",\n"
            + "          \"icon_width\": 56,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"GIAO NGAY 2H - 3H\",\n"
            + "          \"text_color\": \"#009900\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"placement\": \"benefits\",\n"
            + "          \"type\": \"benefits_badge\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/ba/4e/6e/26e9f2487e9f49b7dcf4043960e687dd.png\",\n"
            + "          \"icon_width\": 18,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"Trả góp\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"discount\": 3991000,\n"
            + "      \"discount_rate\": 10,\n"
            + "      \"rating_average\": 5,\n"
            + "      \"review_count\": 19,\n"
            + "      \"order_count\": 0,\n"
            + "      \"favourite_count\": 0,\n"
            + "      \"thumbnail_url\": \"https://salt.tikicdn.com/cache/280x280/ts/product/90/c1/c8/b4a15be982d5744df81cdd54a6ac5d6c.jpg\",\n"
            + "      \"thumbnail_width\": 280,\n"
            + "      \"thumbnail_height\": 280,\n"
            + "      \"has_ebook\": false,\n"
            + "      \"inventory_status\": \"available\",\n"
            + "      \"is_visible\": true,\n"
            + "      \"productset_id\": 2493,\n"
            + "      \"is_flower\": false,\n"
            + "      \"is_gift_card\": false,\n"
            + "      \"inventory\": {\n"
            + "        \"fulfillment_type\": \"tiki_delivery\"\n"
            + "      },\n"
            + "      \"url_attendant_input_form\": \"\",\n"
            + "      \"stock_item\": {\n"
            + "        \"qty\": 5,\n"
            + "        \"min_sale_qty\": 1,\n"
            + "        \"max_sale_qty\": 2,\n"
            + "        \"preorder_date\": false\n"
            + "      },\n"
            + "      \"salable_type\": \"\",\n"
            + "      \"seller_product_id\": 73795664,\n"
            + "      \"installment_info\": {\n"
            + "        \"price\": 5999833,\n"
            + "        \"month\": \"6\",\n"
            + "        \"redirect_url\": \"https://tiki.vn/installment?masterId=73795660&spid=73795664\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": 72537395,\n"
            + "      \"sku\": \"1987704859105\",\n"
            + "      \"name\": \"Laptop Asus VivoBook 15 A515EA-BQ489T (Core i3-1115G4/ 4GB DDR4 3200MHz Onboard/ 512GB SSD M.2 PCIE G3X4/ 15.6 FHD/ Win10) - Hàng Chính Hãng\",\n"
            + "      \"url_key\": \"laptop-asus-vivobook-15-a515ea-bq489t-core-i3-1115g4-4gb-ddr4-3200mhz-onboard-512gb-ssd-m-2-pcie-g3x4-15-6-fhd-win10-hang-chinh-hang-p72537395\",\n"
            + "      \"url_path\": \"laptop-asus-vivobook-15-a515ea-bq489t-core-i3-1115g4-4gb-ddr4-3200mhz-onboard-512gb-ssd-m-2-pcie-g3x4-15-6-fhd-win10-hang-chinh-hang-p72537395.html?src=ss-organic\",\n"
            + "      \"type\": \"simple\",\n"
            + "      \"brand_name\": \"Asus\",\n"
            + "      \"short_description\": \"HIẾT KẾ NĂNG ĐỘNG – TRẺ TRUNG\\nBước sang năm 2020, hãng Asus đã tạo lên một phong cách đột phá mới, với tâm điểm là phím “Enter” và tất nhiên dòng sản phẩm Asus VivoBook A515EA cũng không ngoại lệ. Sở...\",\n"
            + "      \"price\": 13039000,\n"
            + "      \"list_price\": 13990000,\n"
            + "      \"badges\": [\n"
            + "        {\n"
            + "          \"price\": 2173167,\n"
            + "          \"month\": \"6\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"text\": \"Trả góp 0%\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"badges_new\": [\n"
            + "        {\n"
            + "          \"placement\": \"under_price\",\n"
            + "          \"type\": \"under_price_icon\",\n"
            + "          \"code\": \"is_best_price_guaranteed\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/51/ac/cc/528e80fe3f464f910174e2fdf8887b6f.png\",\n"
            + "          \"icon_width\": 124,\n"
            + "          \"icon_height\": 18,\n"
            + "          \"text\": \"\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"placement\": \"benefits\",\n"
            + "          \"type\": \"benefits_badge\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/ba/4e/6e/26e9f2487e9f49b7dcf4043960e687dd.png\",\n"
            + "          \"icon_width\": 18,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"Trả góp\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"discount\": 951000,\n"
            + "      \"discount_rate\": 7,\n"
            + "      \"rating_average\": 5,\n"
            + "      \"review_count\": 13,\n"
            + "      \"order_count\": 0,\n"
            + "      \"favourite_count\": 0,\n"
            + "      \"thumbnail_url\": \"https://salt.tikicdn.com/cache/280x280/ts/product/96/3b/14/e6c7bcb181af815f8c91a2647fb0f3b2.jpg\",\n"
            + "      \"thumbnail_width\": 280,\n"
            + "      \"thumbnail_height\": 280,\n"
            + "      \"has_ebook\": false,\n"
            + "      \"inventory_status\": \"available\",\n"
            + "      \"is_visible\": true,\n"
            + "      \"productset_id\": 2635,\n"
            + "      \"is_flower\": false,\n"
            + "      \"is_gift_card\": false,\n"
            + "      \"inventory\": {\n"
            + "        \"fulfillment_type\": \"tiki_delivery\"\n"
            + "      },\n"
            + "      \"url_attendant_input_form\": \"\",\n"
            + "      \"stock_item\": {\n"
            + "        \"qty\": 9,\n"
            + "        \"min_sale_qty\": 1,\n"
            + "        \"max_sale_qty\": 1,\n"
            + "        \"preorder_date\": false\n"
            + "      },\n"
            + "      \"salable_type\": \"\",\n"
            + "      \"seller_product_id\": 72537396,\n"
            + "      \"installment_info\": {\n"
            + "        \"price\": 2173167,\n"
            + "        \"month\": \"6\",\n"
            + "        \"redirect_url\": \"https://tiki.vn/installment?masterId=72537395&spid=72537396\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": 74556865,\n"
            + "      \"sku\": \"2786497006029\",\n"
            + "      \"name\": \"Laptop Huawei Matebook D 15 (8GB/256GB) - Hàng Phân Phối Chính Hãng\",\n"
            + "      \"url_key\": \"laptop-huawei-matebook-d-15-8gb-256gb-hang-phan-phoi-chinh-hang-p74556865\",\n"
            + "      \"url_path\": \"laptop-huawei-matebook-d-15-8gb-256gb-hang-phan-phoi-chinh-hang-p74556865.html?src=ss-organic\",\n"
            + "      \"type\": \"configurable\",\n"
            + "      \"brand_name\": \"Huawei\",\n"
            + "      \"short_description\": \"\\n \\n\\n\\n\\n\\n \\n\\n\\n\\n\\n \\n\\n\\n\\n \\n\\n\\n\",\n"
            + "      \"price\": 14990000,\n"
            + "      \"list_price\": 14990000,\n"
            + "      \"badges\": [\n"
            + "        {\n"
            + "          \"option\": \"2h\",\n"
            + "          \"code\": \"fast_delivery\",\n"
            + "          \"text\": \"Giao nhanh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"code\": \"tikinow\",\n"
            + "          \"text\": \"tikinow\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"code\": \"leadtime\",\n"
            + "          \"text\": \"GIAO NGAY 2H - 3H\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"price\": 2498333,\n"
            + "          \"month\": \"6\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"text\": \"Trả góp 0%\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"badges_new\": [\n"
            + "        {\n"
            + "          \"placement\": \"service\",\n"
            + "          \"type\": \"service_badge\",\n"
            + "          \"code\": \"tikinow\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/9f/32/dd/8a8d39d4453399569dfb3e80fe01de75.png\",\n"
            + "          \"icon_width\": 56,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"GIAO NGAY 2H - 3H\",\n"
            + "          \"text_color\": \"#009900\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"placement\": \"under_price\",\n"
            + "          \"type\": \"under_price_icon\",\n"
            + "          \"code\": \"is_best_price_guaranteed\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/51/ac/cc/528e80fe3f464f910174e2fdf8887b6f.png\",\n"
            + "          \"icon_width\": 124,\n"
            + "          \"icon_height\": 18,\n"
            + "          \"text\": \"\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"placement\": \"benefits\",\n"
            + "          \"type\": \"benefits_badge\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/ba/4e/6e/26e9f2487e9f49b7dcf4043960e687dd.png\",\n"
            + "          \"icon_width\": 18,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"Trả góp\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"discount\": 0,\n"
            + "      \"discount_rate\": 0,\n"
            + "      \"rating_average\": 5,\n"
            + "      \"review_count\": 15,\n"
            + "      \"order_count\": 0,\n"
            + "      \"favourite_count\": 0,\n"
            + "      \"thumbnail_url\": \"https://salt.tikicdn.com/cache/280x280/ts/product/ab/16/14/4240db4a8b83412871826b3761a995b9.jpg\",\n"
            + "      \"thumbnail_width\": 280,\n"
            + "      \"thumbnail_height\": 280,\n"
            + "      \"has_ebook\": false,\n"
            + "      \"inventory_status\": \"available\",\n"
            + "      \"is_visible\": true,\n"
            + "      \"productset_id\": 53,\n"
            + "      \"is_flower\": false,\n"
            + "      \"is_gift_card\": false,\n"
            + "      \"inventory\": {\n"
            + "        \"fulfillment_type\": \"tiki_delivery\"\n"
            + "      },\n"
            + "      \"url_attendant_input_form\": \"\",\n"
            + "      \"stock_item\": {\n"
            + "        \"qty\": 22,\n"
            + "        \"min_sale_qty\": 1,\n"
            + "        \"max_sale_qty\": 20,\n"
            + "        \"preorder_date\": false\n"
            + "      },\n"
            + "      \"salable_type\": \"\",\n"
            + "      \"seller_product_id\": 74556869,\n"
            + "      \"installment_info\": {\n"
            + "        \"price\": 2498333,\n"
            + "        \"month\": \"6\",\n"
            + "        \"redirect_url\": \"https://tiki.vn/installment?masterId=74556865&spid=74556869\"\n"
            + "      }\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": 70833240,\n"
            + "      \"sku\": \"2280571527450\",\n"
            + "      \"name\": \"Laptop HP Envy 13-ba1027TU 2K0B1PA (Core i5-1135G7/ 8GB DDR4 3200MHz (Onboard)/ 256GB PCIe NVMe M.2/ 13.3 FHD IPS/ Win10) - Hàng Chính Hãng\",\n"
            + "      \"url_key\": \"laptop-hp-envy-13-ba1027tu-2k0b1pa-core-i5-1135g7-8gb-ddr4-3200mhz-onboard-256gb-pcie-nvme-m-2-13-3-fhd-ips-win10-hang-chinh-hang-p70833240\",\n"
            + "      \"url_path\": \"laptop-hp-envy-13-ba1027tu-2k0b1pa-core-i5-1135g7-8gb-ddr4-3200mhz-onboard-256gb-pcie-nvme-m-2-13-3-fhd-ips-win10-hang-chinh-hang-p70833240.html?src=ss-organic\",\n"
            + "      \"type\": \"simple\",\n"
            + "      \"brand_name\": \"HP\",\n"
            + "      \"short_description\": \"Thiết kế nhỏ gọn tiện lợi\\nLaptop HP Envy 13-ba1027TU 2K0B1PA có kích thước nhỏ gọn siêu di động nhờ thiết kế viền mỏng và chế tác bằng chất liệu kim loại nguyên khối màu bạc đẹp mắt. Đây dường như là...\",\n"
            + "      \"price\": 21199000,\n"
            + "      \"list_price\": 22990000,\n"
            + "      \"badges\": [\n"
            + "        {\n"
            + "          \"price\": 3533167,\n"
            + "          \"month\": \"6\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"text\": \"Trả góp 0%\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"badges_new\": [\n"
            + "        {\n"
            + "          \"placement\": \"under_price\",\n"
            + "          \"type\": \"under_price_icon\",\n"
            + "          \"code\": \"is_best_price_guaranteed\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/51/ac/cc/528e80fe3f464f910174e2fdf8887b6f.png\",\n"
            + "          \"icon_width\": 124,\n"
            + "          \"icon_height\": 18,\n"
            + "          \"text\": \"\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"placement\": \"benefits\",\n"
            + "          \"type\": \"benefits_badge\",\n"
            + "          \"code\": \"installment\",\n"
            + "          \"icon\": \"https://salt.tikicdn.com/ts/upload/ba/4e/6e/26e9f2487e9f49b7dcf4043960e687dd.png\",\n"
            + "          \"icon_width\": 18,\n"
            + "          \"icon_height\": 16,\n"
            + "          \"text\": \"Trả góp\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"discount\": 1791000,\n"
            + "      \"discount_rate\": 8,\n"
            + "      \"rating_average\": 4.8,\n"
            + "      \"review_count\": 21,\n"
            + "      \"order_count\": 0,\n"
            + "      \"favourite_count\": 0,\n"
            + "      \"thumbnail_url\": \"https://salt.tikicdn.com/cache/280x280/ts/product/58/c8/ba/1d0bde7776e2d0e90ab4972f58a997e3.jpg\",\n"
            + "      \"thumbnail_width\": 280,\n"
            + "      \"thumbnail_height\": 280,\n"
            + "      \"has_ebook\": false,\n"
            + "      \"inventory_status\": \"available\",\n"
            + "      \"is_visible\": true,\n"
            + "      \"productset_id\": 2635,\n"
            + "      \"is_flower\": false,\n"
            + "      \"is_gift_card\": false,\n"
            + "      \"inventory\": {\n"
            + "        \"fulfillment_type\": \"tiki_delivery\"\n"
            + "      },\n"
            + "      \"url_attendant_input_form\": \"\",\n"
            + "      \"stock_item\": {\n"
            + "        \"qty\": 12,\n"
            + "        \"min_sale_qty\": 1,\n"
            + "        \"max_sale_qty\": 1,\n"
            + "        \"preorder_date\": false\n"
            + "      },\n"
            + "      \"salable_type\": \"\",\n"
            + "      \"seller_product_id\": 70833242,\n"
            + "      \"installment_info\": {\n"
            + "        \"price\": 3533167,\n"
            + "        \"month\": \"6\",\n"
            + "        \"redirect_url\": \"https://tiki.vn/installment?masterId=70833240&spid=70833242\"\n"
            + "      }\n"
            + "    }\n"
            + "  ],\n"
            + "  \"paging\": {\n"
            + "    \"total\": 245,\n"
            + "    \"per_page\": 10,\n"
            + "    \"current_page\": 1,\n"
            + "    \"last_page\": 25,\n"
            + "    \"from\": 1,\n"
            + "    \"to\": 10\n"
            + "  },\n"
            + "  \"widgets\": [\n"
            + "    {\n"
            + "      \"code\": \"suggested_filters_inline\",\n"
            + "      \"placement\": \"inline\",\n"
            + "      \"position\": 11,\n"
            + "      \"type\": \"suggested_filters_inline\",\n"
            + "      \"title\": \"Bộ Lọc Phổ Biến\",\n"
            + "      \"items\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Dell\",\n"
            + "          \"query_name\": \"brand\",\n"
            + "          \"display_name\": \"Thương hiệu\",\n"
            + "          \"query_value\": \"18805\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Asus\",\n"
            + "          \"query_name\": \"brand\",\n"
            + "          \"display_name\": \"Thương hiệu\",\n"
            + "          \"query_value\": \"17826\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Tiki Trading\",\n"
            + "          \"query_name\": \"seller\",\n"
            + "          \"display_name\": \"Nhà cung cấp\",\n"
            + "          \"query_value\": \"1\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"HP\",\n"
            + "          \"query_name\": \"brand\",\n"
            + "          \"display_name\": \"Thương hiệu\",\n"
            + "          \"query_value\": \"17825\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Có\",\n"
            + "          \"query_name\": \"support_p2h_delivery\",\n"
            + "          \"display_name\": \"Giao nhanh\",\n"
            + "          \"query_value\": \"1\"\n"
            + "        }\n"
            + "      ]\n"
            + "    },\n"
            + "    {\n"
            + "      \"code\": \"popular_filters_inline\",\n"
            + "      \"multi_select\": true,\n"
            + "      \"placement\": \"inline\",\n"
            + "      \"position\": 21,\n"
            + "      \"type\": \"popular_filters_inline\",\n"
            + "      \"title\": \"Thương hiệu\",\n"
            + "      \"items\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Dell\",\n"
            + "          \"query_name\": \"brand\",\n"
            + "          \"query_value\": \"18805\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Asus\",\n"
            + "          \"query_name\": \"brand\",\n"
            + "          \"query_value\": \"17826\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"HP\",\n"
            + "          \"query_name\": \"brand\",\n"
            + "          \"query_value\": \"17825\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Acer\",\n"
            + "          \"query_name\": \"brand\",\n"
            + "          \"query_value\": \"18803\"\n"
            + "        }\n"
            + "      ]\n"
            + "    }\n"
            + "  ],\n"
            + "  \"sort_options\": [\n"
            + "    {\n"
            + "      \"display_value\": \"Phổ biến\",\n"
            + "      \"query_value\": \"default\",\n"
            + "      \"selected\": true\n"
            + "    },\n"
            + "    {\n"
            + "      \"display_value\": \"Bán chạy\",\n"
            + "      \"query_value\": \"top_seller\",\n"
            + "      \"selected\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"display_value\": \"Hàng mới\",\n"
            + "      \"query_value\": \"newest\",\n"
            + "      \"selected\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"display_value\": \"Giá thấp\",\n"
            + "      \"query_value\": \"price,asc\",\n"
            + "      \"selected\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"display_value\": \"Giá cao\",\n"
            + "      \"query_value\": \"price,desc\",\n"
            + "      \"selected\": false\n"
            + "    }\n"
            + "  ],\n"
            + "  \"filters\": [\n"
            + "    {\n"
            + "      \"query_name\": \"category\",\n"
            + "      \"display_name\": \"Danh Mục Sản Phẩm\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Laptop Truyền Thống\",\n"
            + "          \"count\": 182,\n"
            + "          \"query_value\": 29010,\n"
            + "          \"url_key\": \"laptop-truyen-thong\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Laptop Gaming\",\n"
            + "          \"count\": 38,\n"
            + "          \"query_value\": 5584,\n"
            + "          \"url_key\": \"laptop-gaming\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Laptop 2 trong 1\",\n"
            + "          \"count\": 23,\n"
            + "          \"query_value\": 29008,\n"
            + "          \"url_key\": \"laptop-2-trong-1\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Macbook\",\n"
            + "          \"count\": 10,\n"
            + "          \"query_value\": 2458,\n"
            + "          \"url_key\": \"macbook-imac\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"support_p2h_delivery\",\n"
            + "      \"display_name\": \"Giao hàng nhanh 2h\",\n"
            + "      \"type\": \"service\",\n"
            + "      \"icon\": \"https://salt.tikicdn.com/ts/upload/9f/32/dd/8a8d39d4453399569dfb3e80fe01de75.png\",\n"
            + "      \"icon_width\": 56,\n"
            + "      \"icon_height\": 16,\n"
            + "      \"sticky\": true,\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Có\",\n"
            + "          \"count\": 145,\n"
            + "          \"query_value\": \"1\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"rating\",\n"
            + "      \"display_name\": \"Đánh giá\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"từ 5 sao\",\n"
            + "          \"query_value\": \"5\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"từ 4 sao\",\n"
            + "          \"query_value\": \"4\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"từ 3 sao\",\n"
            + "          \"query_value\": \"3\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"free_ship_badge\",\n"
            + "      \"display_name\": \"Miễn phí giao hàng\",\n"
            + "      \"type\": \"service\",\n"
            + "      \"sticky\": true,\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Có\",\n"
            + "          \"count\": 45,\n"
            + "          \"query_value\": \"true\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"is_best_price_guaranteed\",\n"
            + "      \"display_name\": \"Rẻ hơn hoàn tiền\",\n"
            + "      \"type\": \"service\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Có\",\n"
            + "          \"count\": 93,\n"
            + "          \"query_value\": 1\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"price\",\n"
            + "      \"display_name\": \"Giá\",\n"
            + "      \"min\": 0,\n"
            + "      \"max\": 10000000000,\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Dưới 13.500.000\",\n"
            + "          \"count\": 15287,\n"
            + "          \"query_value\": \"0,13500000\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Từ 13.500.000 đến 21.500.000\",\n"
            + "          \"count\": 15287,\n"
            + "          \"query_value\": \"13500000,21500000\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Từ 21.500.000 đến 31.000.000\",\n"
            + "          \"count\": 15287,\n"
            + "          \"query_value\": \"21500000,31000000\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Trên 31.000.000\",\n"
            + "          \"count\": 15287,\n"
            + "          \"query_value\": \"31000000,10000000000\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"brand\",\n"
            + "      \"display_name\": \"Thương hiệu\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"HP\",\n"
            + "          \"count\": 46,\n"
            + "          \"query_value\": \"17825\",\n"
            + "          \"url_key\": \"thuong-hieu/hp.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Acer\",\n"
            + "          \"count\": 44,\n"
            + "          \"query_value\": \"18803\",\n"
            + "          \"url_key\": \"thuong-hieu/acer.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Asus\",\n"
            + "          \"count\": 34,\n"
            + "          \"query_value\": \"17826\",\n"
            + "          \"url_key\": \"thuong-hieu/asus.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Lenovo\",\n"
            + "          \"count\": 27,\n"
            + "          \"query_value\": \"249593,18604\",\n"
            + "          \"url_key\": \"thuong-hieu/lenovo.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Dell\",\n"
            + "          \"count\": 26,\n"
            + "          \"query_value\": \"18805\",\n"
            + "          \"url_key\": \"thuong-hieu/dell.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"MSI\",\n"
            + "          \"count\": 24,\n"
            + "          \"query_value\": \"49067\",\n"
            + "          \"url_key\": \"thuong-hieu/msi.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Apple\",\n"
            + "          \"count\": 10,\n"
            + "          \"query_value\": \"17827\",\n"
            + "          \"url_key\": \"thuong-hieu/apple.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Microsoft\",\n"
            + "          \"count\": 9,\n"
            + "          \"query_value\": \"19246\",\n"
            + "          \"url_key\": \"thuong-hieu/microsoft.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Surface\",\n"
            + "          \"count\": 7,\n"
            + "          \"query_value\": \"111973\",\n"
            + "          \"url_key\": \"thuong-hieu/surface.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Avita \",\n"
            + "          \"count\": 5,\n"
            + "          \"query_value\": \"26216\",\n"
            + "          \"url_key\": \"thuong-hieu/avita.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"LG\",\n"
            + "          \"count\": 5,\n"
            + "          \"query_value\": \"18851\",\n"
            + "          \"url_key\": \"thuong-hieu/lg.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Huawei\",\n"
            + "          \"count\": 3,\n"
            + "          \"query_value\": \"19788\",\n"
            + "          \"url_key\": \"thuong-hieu/huawei.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"OEM\",\n"
            + "          \"count\": 2,\n"
            + "          \"query_value\": \"111461\",\n"
            + "          \"url_key\": \"thuong-hieu/oem.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"HP.\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"500891\",\n"
            + "          \"url_key\": \"thuong-hieu/hp.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Hyper\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"158307\",\n"
            + "          \"url_key\": \"thuong-hieu/hyper.html\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Tomtoc\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"252755\",\n"
            + "          \"url_key\": \"thuong-hieu/tomtoc.html\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": true\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"filter_laptop_card\",\n"
            + "      \"display_name\": \"VGA Card\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Intel UHD Graphic\",\n"
            + "          \"count\": 12,\n"
            + "          \"query_value\": \"204757\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Intel Iris\",\n"
            + "          \"count\": 11,\n"
            + "          \"query_value\": \"63873\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Intel UHD Graphics 620\",\n"
            + "          \"count\": 9,\n"
            + "          \"query_value\": \"155193\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"NVIDIA Geforce GTX\",\n"
            + "          \"count\": 7,\n"
            + "          \"query_value\": \"63878\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Intel HD Graphic\",\n"
            + "          \"count\": 4,\n"
            + "          \"query_value\": \"63874\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Intel® UHD Graphics 620\",\n"
            + "          \"count\": 3,\n"
            + "          \"query_value\": \"155165\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Intel Iris Plus Graphics 640\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"160197\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": true\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"filter_laptop_cpu\",\n"
            + "      \"display_name\": \"CPU\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Intel Core i5\",\n"
            + "          \"count\": 26,\n"
            + "          \"query_value\": \"63849\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Intel Core i3\",\n"
            + "          \"count\": 13,\n"
            + "          \"query_value\": \"63850\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Intel Core i7\",\n"
            + "          \"count\": 13,\n"
            + "          \"query_value\": \"63848\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Intel Celeron\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"63852\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Intel Pentium\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"63853\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": true\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"filter_laptop_hard_disk_type\",\n"
            + "      \"display_name\": \"Loại ổ cứng\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"SSD\",\n"
            + "          \"count\": 49,\n"
            + "          \"query_value\": \"63860\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"HDD\",\n"
            + "          \"count\": 9,\n"
            + "          \"query_value\": \"63861\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"DDR4\",\n"
            + "          \"count\": 6,\n"
            + "          \"query_value\": \"154927\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"SSD + HDD\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"160901\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": true\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"filter_laptop_memory\",\n"
            + "      \"display_name\": \"RAM\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"8GB\",\n"
            + "          \"count\": 35,\n"
            + "          \"query_value\": \"63858\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"4GB\",\n"
            + "          \"count\": 24,\n"
            + "          \"query_value\": \"63857\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": true\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"filter_laptop_screen_size\",\n"
            + "      \"display_name\": \"Kích thước màn hình\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"15.6 inch\",\n"
            + "          \"count\": 45,\n"
            + "          \"query_value\": \"63882\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"14 inch\",\n"
            + "          \"count\": 34,\n"
            + "          \"query_value\": \"63883\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"13.3 inch\",\n"
            + "          \"count\": 11,\n"
            + "          \"query_value\": \"154855\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"12.3 inch\",\n"
            + "          \"count\": 5,\n"
            + "          \"query_value\": \"166933\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"15 inch\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"160149\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"17.3 inch\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"155421\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": true\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"filter_laptop_series\",\n"
            + "      \"display_name\": \"Series\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"HP Pavilion\",\n"
            + "          \"count\": 5,\n"
            + "          \"query_value\": \"63828\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Acer Aspire A\",\n"
            + "          \"count\": 4,\n"
            + "          \"query_value\": \"154921\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Asus Vivobook\",\n"
            + "          \"count\": 4,\n"
            + "          \"query_value\": \"160897\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Surface Pro 2018\",\n"
            + "          \"count\": 4,\n"
            + "          \"query_value\": \"254095\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Acer Aspire E\",\n"
            + "          \"count\": 3,\n"
            + "          \"query_value\": \"63807\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Lenovo Ideapad\",\n"
            + "          \"count\": 3,\n"
            + "          \"query_value\": \"63830\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Dell Inspiron\",\n"
            + "          \"count\": 2,\n"
            + "          \"query_value\": \"63818\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"HP Probook\",\n"
            + "          \"count\": 2,\n"
            + "          \"query_value\": \"63827\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Acer Nitro 5\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"160623\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Acer Swift 3\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"114182\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Asus P Series\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"63812\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Asus TP Series\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"63810\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Dell Vostro\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"63815\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"HP 14/15\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"63822\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"HP Envy\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"63820\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Lenovo Thinkpad\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"63832\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": true\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"filter_laptop_storage\",\n"
            + "      \"display_name\": \"Dung lượng lưu trữ\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"256GB\",\n"
            + "          \"count\": 29,\n"
            + "          \"query_value\": \"156953\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"512GB\",\n"
            + "          \"count\": 21,\n"
            + "          \"query_value\": \"158537\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"1TB\",\n"
            + "          \"count\": 11,\n"
            + "          \"query_value\": \"63865\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"128GB\",\n"
            + "          \"count\": 2,\n"
            + "          \"query_value\": \"156957\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"240 GB - 256 GB\",\n"
            + "          \"count\": 2,\n"
            + "          \"query_value\": \"63868\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"120 GB - 192 GB\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"63869\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"128GB + 1TB\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"156955\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": true\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"filter_laptop_system\",\n"
            + "      \"display_name\": \"Hệ điều hành\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Windows bản quyền\",\n"
            + "          \"count\": 60,\n"
            + "          \"query_value\": \"63890\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Free Dos\",\n"
            + "          \"count\": 6,\n"
            + "          \"query_value\": \"63889\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Mac OS X\",\n"
            + "          \"count\": 2,\n"
            + "          \"query_value\": \"63891\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": true\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"filter_laptop_touch\",\n"
            + "      \"display_name\": \"Cảm ứng\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Có\",\n"
            + "          \"count\": 11,\n"
            + "          \"query_value\": \"63887\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Không\",\n"
            + "          \"count\": 42,\n"
            + "          \"query_value\": \"63888\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": false\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"option_color\",\n"
            + "      \"display_name\": \"Màu sắc\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Xám\",\n"
            + "          \"count\": 7,\n"
            + "          \"query_value\": \"Xám\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Bạc\",\n"
            + "          \"count\": 5,\n"
            + "          \"query_value\": \"Bạc\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Đen\",\n"
            + "          \"count\": 3,\n"
            + "          \"query_value\": \"Đen\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Vàng\",\n"
            + "          \"count\": 2,\n"
            + "          \"query_value\": \"Vàng\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Xanh\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"Xanh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Đỏ\",\n"
            + "          \"count\": 1,\n"
            + "          \"query_value\": \"Đỏ\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": true\n"
            + "    },\n"
            + "    {\n"
            + "      \"query_name\": \"seller\",\n"
            + "      \"display_name\": \"Nhà cung cấp\",\n"
            + "      \"values\": [\n"
            + "        {\n"
            + "          \"display_value\": \"Tiki Trading\",\n"
            + "          \"count\": 139,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/ee/fa/a0/98f3f134f85cff2c6972c31777629aa0.png\",\n"
            + "          \"query_value\": 1,\n"
            + "          \"seller_address\": \"\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"CIVIP Technology\",\n"
            + "          \"count\": 34,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/fc/66/4e/ae6037a65c0a630fd04be6c4907deb9c.jpg\",\n"
            + "          \"query_value\": 156976,\n"
            + "          \"seller_address\": \"750 Quang Trung, Phường Chánh Lộ, Thành phố Quảng Ngãi, Quảng Ngãi\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Vi Tính Bảo An\",\n"
            + "          \"count\": 15,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/6d/b1/8e/376ca7e2b13cd2285cbfd75fbca16509.jpg\",\n"
            + "          \"query_value\": 1377,\n"
            + "          \"seller_address\": \".250 Cao Thắng Nối dài, Phường 12, Quận 10, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Của Hàng LAPTOPST\",\n"
            + "          \"count\": 15,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/4b/54/1a/f385a79a716cb3505f152e7af8c769aa.png\",\n"
            + "          \"query_value\": 157993,\n"
            + "          \"seller_address\": \"529/2B Điện Biên Phủ, Phường 3, Quận 3, TPHCM, Phường 03, Quận 3, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"NewTechShop\",\n"
            + "          \"count\": 14,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/f6/a4/7b/462f57ec9fddfda4fac644066505611f.png\",\n"
            + "          \"query_value\": 52979,\n"
            + "          \"seller_address\": \"102A Phùng Văn Cung, Phường 07, Quận Phú Nhuận, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Mega Technology\",\n"
            + "          \"count\": 9,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/22/43/03/82f1a968fc05ee3150fc0aca1c72afe3.jpg\",\n"
            + "          \"query_value\": 8305,\n"
            + "          \"seller_address\": \"130 Hàm Nghi, Phường Thạc Gián, Quận Thanh Khê, Đà Nẵng\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"SURFACEVIET\",\n"
            + "          \"count\": 7,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/55/9f/2c/a493979c9ccfba8a61babf0fb0993cd4.png\",\n"
            + "          \"query_value\": 11960,\n"
            + "          \"seller_address\": \"43/4 thành thái, p14, q10, HCM, Phường 14, Quận 10, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"NGUYENVUSTORE\",\n"
            + "          \"count\": 7,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/53/c3/30/e5ce9ab28e0b91da9ca4e15808e9e70c.jpg\",\n"
            + "          \"query_value\": 27572,\n"
            + "          \"seller_address\": \"58 - 60 đường Lê Bình, P. Hưng Lợi, Phường Hưng Lợi, Quận Ninh Kiều, Cần Thơ\\t, Phường Hưng Lợi, Quận Ninh Kiều, Cần Thơ\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Hanoi computer\",\n"
            + "          \"count\": 5,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/2b/45/01/bc5fdb3ef575d63f47a6b32eb2fa6590.jpg\",\n"
            + "          \"query_value\": 21125,\n"
            + "          \"seller_address\": \"131 LÊ THANH NGHỊ, HAI BÀ TRƯNG, HÀ NỘI, Phường Đồng Tâm, Quận Hai Bà Trưng, Hà Nội\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Hà Nội Lab\",\n"
            + "          \"count\": 4,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/b6/ac/8e/008f0082a4a34ee9494e17ab6ac1dc66.png\",\n"
            + "          \"query_value\": 19749,\n"
            + "          \"seller_address\": \"Ô số 3, tầng 5, tháp A, tòa nhà D2 Giảng Võ, số 144 - đường Giảng Võ, Phường Giảng Võ, Quận Ba Đình, Hà Nội\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"HP Official Store\",\n"
            + "          \"count\": 3,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/bf/ee/ce/74caf67db1b24f9413f7197a1cdc4127.png\",\n"
            + "          \"query_value\": 41387,\n"
            + "          \"seller_address\": \"Số 6A Thăng Long (trả hàng ở cửa kho, không lấy được ngoài cổng Khu Công Nghiệp), Phường 04, Quận Tân Bình, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Thiết bị tin học Quảng Tin\",\n"
            + "          \"count\": 3,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/e7/ef/52/e596f2738cf229eda3adf440dc22c7dc.jpg\",\n"
            + "          \"query_value\": 60710,\n"
            + "          \"seller_address\": \"6D3 CHU VĂN AN, Phường 26, Quận Bình Thạnh, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Huawei Flagship Store\",\n"
            + "          \"count\": 3,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/d3/f4/27/c7a14894008225dd4e68ae472909d39b.jpg\",\n"
            + "          \"query_value\": 161312,\n"
            + "          \"seller_address\": \"6 Tân Thới Nhất 8, Phường Tân Thới Nhất, Quận 12, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Xuân Vinh Computer\",\n"
            + "          \"count\": 2,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/4b/54/1a/f385a79a716cb3505f152e7af8c769aa.png\",\n"
            + "          \"query_value\": 16762,\n"
            + "          \"seller_address\": \"92-94 Hàm Nghi, Phường Thạc Gián, Quận Thanh Khê, Đà Nẵng\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Detico\",\n"
            + "          \"count\": 2,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/4b/54/1a/f385a79a716cb3505f152e7af8c769aa.png\",\n"
            + "          \"query_value\": 19548,\n"
            + "          \"seller_address\": \"P1107 Tòa nhà N03 38 Trần Quý Kiên, Phường Dịch Vọng, Quận Cầu Giấy, Hà Nội\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"CICI LAPTOP\",\n"
            + "          \"count\": 2,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/4b/54/1a/f385a79a716cb3505f152e7af8c769aa.png\",\n"
            + "          \"query_value\": 19628,\n"
            + "          \"seller_address\": \"CT4 . Tam Đảo, Phường 15, Quận 10, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"congnghemoi\",\n"
            + "          \"count\": 2,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/23/2a/f0/eec4ea155129c9d97dee08a75b1d9f7f.jpg\",\n"
            + "          \"query_value\": 27707,\n"
            + "          \"seller_address\": \"47/3/8 vườn lài, Phường An Phú Đông, Quận 12, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Đức Anh Computer\",\n"
            + "          \"count\": 2,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/4b/54/1a/f385a79a716cb3505f152e7af8c769aa.png\",\n"
            + "          \"query_value\": 62751,\n"
            + "          \"seller_address\": \"35/4 bùi quang là,phường 12,quận gò vấp, Phường 12, Quận Gò Vấp, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Antam Trading\",\n"
            + "          \"count\": 1,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/8c/69/d8/3c6fc7c001956cc32a1b1c426fd3f6ad.png\",\n"
            + "          \"query_value\": 10016,\n"
            + "          \"seller_address\": \"Số 48 ngách 1/8 Ngõ 1, đường Đình Thôn, Phường Mỹ Đình 1, Quận Nam Từ Liêm, Hà Nội\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"ThuanThienTs\",\n"
            + "          \"count\": 1,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/de/e1/fa/5e205d4b1e4b52bc22c1ee3932db472f.jpg\",\n"
            + "          \"query_value\": 12854,\n"
            + "          \"seller_address\": \"6/18 Đường 20, Phường Linh Đông, Quận Thủ Đức, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"FT&T\",\n"
            + "          \"count\": 1,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/14/c4/00/98b155fa152181bdffff99dcbf69be81.png\",\n"
            + "          \"query_value\": 18637,\n"
            + "          \"seller_address\": \"184 Phan Đăng Lưu, Phường 03, Quận Phú Nhuận, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"GiaPhucStore\",\n"
            + "          \"count\": 1,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/ae/7b/02/aa5a3c57083e649536b88024fc51ab95.jpg\",\n"
            + "          \"query_value\": 34716,\n"
            + "          \"seller_address\": \"437F Mã Lò, Phường Bình Hưng Hoà A, Quận Bình Tân, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Clickshop2019\",\n"
            + "          \"count\": 1,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/e9/9d/f1/3954232a10e08a8ce5ec6feed7ea0587.jpg\",\n"
            + "          \"query_value\": 53535,\n"
            + "          \"seller_address\": \"382/30 Nguyễn Thị Minh Khai, Phường 05, Quận 3, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Cotimex Đà Nẵng\",\n"
            + "          \"count\": 1,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/4b/54/1a/f385a79a716cb3505f152e7af8c769aa.png\",\n"
            + "          \"query_value\": 53851,\n"
            + "          \"seller_address\": \"123 Nguyễn Chí Thanh, P. Hải Châu 1, Q.Hải Châu, TP. Đà Nẵng, Phường Hải Châu I, Quận Hải Châu, Đà Nẵng\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Thiết Bị Văn phòng Anh Dũng\",\n"
            + "          \"count\": 1,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/bf/81/52/1f5fb4112cf01f563319f42819e35823.jpg\",\n"
            + "          \"query_value\": 174763,\n"
            + "          \"seller_address\": \"Số 8 Đường số 12, Cư xá Chu Văn An, Phường 26, Quận Bình Thạnh, Hồ Chí Minh\"\n"
            + "        },\n"
            + "        {\n"
            + "          \"display_value\": \"Shop Phuthuy\",\n"
            + "          \"count\": 1,\n"
            + "          \"logo\": \"https://salt.tikicdn.com/ts/seller/4b/54/1a/f385a79a716cb3505f152e7af8c769aa.png\",\n"
            + "          \"query_value\": 181464,\n"
            + "          \"seller_address\": \"ct7j dương nội hà đông, Phường Dương Nội, Quận Hà Đông, Hà Nội\"\n"
            + "        }\n"
            + "      ],\n"
            + "      \"collapsed\": 5,\n"
            + "      \"multi_select\": false\n"
            + "    }\n"
            + "  ]";
        List<TikiProduct> listObject = JacksonHelper.getUnescapedInstance().readValue(test, new TypeReference<List<TikiProduct>>() {
        });

        System.out.println("readValue = " + listObject.toString());

    }
}
